# -*- coding: utf-8 -*-
"""CustomerBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PfDcOyOkAyLm6P_b0pV-p0PVk9SZDD2E
"""

!pip install pytesseract pdf2image PyMuPDF gradio langchain langgraph langchain_groq
!apt-get install -y poppler-utils tesseract-ocr

!pip install speechrecognition

# !pip install gradio langchain langgraph langchain-groq pytesseract PyMuPDF SpeechRecognition --quiet

import gradio as gr
from typing import Dict
import pytesseract
import fitz  # PyMuPDF
import os
import csv
import speech_recognition as sr
from langchain_groq import ChatGroq
from langgraph.graph import StateGraph, END
from langchain_core.prompts import ChatPromptTemplate
from typing import TypedDict

# ------------------- STATE -------------------
class State(TypedDict):
    query: str
    category: str
    sentiment: str
    response: str

# ------------------- LLM -------------------
llm = ChatGroq(
    temperature=0,
    groq_api_key="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",  # Replace with your real API key
    model_name="llama-3.3-70b-versatile"
)

# ------------------- NODES -------------------
def categorize(state: State) -> State:
    prompt = ChatPromptTemplate.from_template(
        "Categorize this query into: Technical, Billing, or General.\nQuery: {query}"
    )
    return {**state, "category": (prompt | llm).invoke({"query": state["query"]}).content.strip()}

def analyze_sentiment(state: State) -> State:
    prompt = ChatPromptTemplate.from_template(
        "Sentiment of this query? Respond with: Positive, Negative, or Neutral.\nQuery: {query}"
    )
    return {**state, "sentiment": (prompt | llm).invoke({"query": state["query"]}).content.strip()}

def handle_technical(state: State) -> State:
    prompt = ChatPromptTemplate.from_template("Give a technical support response:\n{query}")
    return {**state, "response": (prompt | llm).invoke({"query": state["query"]}).content.strip()}

def handle_billing(state: State) -> State:
    prompt = ChatPromptTemplate.from_template("Give a billing support response:\n{query}")
    return {**state, "response": (prompt | llm).invoke({"query": state["query"]}).content.strip()}

def handle_general(state: State) -> State:
    prompt = ChatPromptTemplate.from_template("Give a general support response:\n{query}")
    return {**state, "response": (prompt | llm).invoke({"query": state["query"]}).content.strip()}

def escalate(state: State) -> State:
    return {**state, "response": "This has been escalated to a human due to negative sentiment."}

def route_query(state: State) -> str:
    if state["sentiment"].lower() == "negative":
        return "escalate"
    if state["category"].lower() == "technical":
        return "handle_technical"
    if state["category"].lower() == "billing":
        return "handle_billing"
    return "handle_general"

# ------------------- GRAPH -------------------
workflow = StateGraph(State)
workflow.add_node("categorize", categorize)
workflow.add_node("analyze_sentiment", analyze_sentiment)
workflow.add_node("handle_technical", handle_technical)
workflow.add_node("handle_billing", handle_billing)
workflow.add_node("handle_general", handle_general)
workflow.add_node("escalate", escalate)

workflow.add_edge("categorize", "analyze_sentiment")
workflow.add_conditional_edges("analyze_sentiment", route_query, {
    "handle_technical": "handle_technical",
    "handle_billing": "handle_billing",
    "handle_general": "handle_general",
    "escalate": "escalate"
})
workflow.set_entry_point("categorize")

for node in ["handle_technical", "handle_billing", "handle_general", "escalate"]:
    workflow.add_edge(node, END)

app = workflow.compile()

# ------------------- OCR / AUDIO -------------------
feedback_dict = {}

def extract_text_from_file(file_path):
    ext = os.path.splitext(file_path)[1].lower()
    if ext in [".png", ".jpg", ".jpeg"]:
        return pytesseract.image_to_string(file_path)
    elif ext == ".pdf":
        doc = fitz.open(file_path)
        return "\n".join(page.get_text() for page in doc)
    return ""

def run_customer_support(query: str) -> Dict[str, str]:
    return app.invoke({"query": query})

def full_interface(audio, text, file, feedback):
    query = text
    if file:
        query = extract_text_from_file(file.name) or query
    if not query and audio:
        recognizer = sr.Recognizer()
        with sr.AudioFile(audio) as source:
            audio_data = recognizer.record(source)
            try:
                query = recognizer.recognize_google(audio_data)
            except:
                return "⚠️ Voice recognition failed."
    if not query:
        return "⚠️ Please provide input."

    result = run_customer_support(query)
    feedback_dict[query] = feedback or "N/A"
    return (
        f"#### 📝 Query:\n{query}\n\n"
        f"#### 🗂️ Category: `{result['category']}`\n"
        f"#### 📊 Sentiment: `{result['sentiment']}`\n\n"
        f"---\n"
        f"### 💬 Response:\n{result['response']}\n\n"
        f"#### 🧭 Feedback: `{feedback or 'N/A'}`"
    )

def export_history():
    file_path = "/content/query_history.csv"
    with open(file_path, "w", newline="") as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(["Query", "Feedback"])
        for query, fb in feedback_dict.items():
            writer.writerow([query, fb])
    return file_path

# ------------------- CUSTOM CSS -------------------
custom_css = """
.gradio-container {
    background: linear-gradient(to right, #f5f7fa, #c3cfe2);
    font-family: 'Segoe UI', sans-serif;
    padding: 20px;
}
textarea, input[type="text"] {
    border-radius: 10px !important;
    padding: 14px !important;
    font-size: 16px !important;
    background-color: #ffffff !important;
}
.gr-button {
    border-radius: 10px !important;
    font-size: 16px !important;
    font-weight: 600 !important;
}
.gr-markdown {
    background-color: #ffffff;
    padding: 20px;
    border-radius: 16px;
    border: 1px solid #ddd;
    margin-top: 10px;
    box-shadow: 0px 4px 10px rgba(0,0,0,0.05);
}
"""

# ------------------- GRADIO UI -------------------
with gr.Blocks(css=custom_css, theme=gr.themes.Soft()) as gui:
    gr.Markdown("## 🤖 **AI Customer Support Assistant**")
    gr.Markdown("Smart responses for your queries via **voice**, **text**, or **file**.")

    with gr.Row():
        audio_input = gr.Audio(label="🎙️ Upload Audio", type="filepath")  # Fixed this line
        text_input = gr.Textbox(lines=2, label="💬 Enter your query")

    file_input = gr.File(label="📎 Upload File (PDF/Image)", file_types=[".pdf", ".png", ".jpg", ".jpeg"])
    feedback = gr.Dropdown(["Yes", "No"], label="🧭 Was this helpful?", multiselect=False)

    with gr.Row():
        submit_btn = gr.Button("🚀 Submit")
        clear_btn = gr.Button("🧹 Clear Output")
        download_btn = gr.Button("⬇️ Download History")

    output = gr.Markdown()

    submit_btn.click(fn=full_interface, inputs=[audio_input, text_input, file_input, feedback], outputs=output)
    clear_btn.click(fn=lambda: "", outputs=output)
    download_btn.click(fn=export_history, outputs=gr.File())

# Launch the UI
gui.launch(share=True)

